export * from './ConsultaCliente'
export * from './ConsultaStock';
export * from './Dashboard';
export * from './DashboardTaller';
export * from './Estadisticas';
export * from './Footer';
export * from './Home';
export * from './ListaEmpleados';
export * from './Logo';
export * from './LogoPantallaCarga';
export * from './Navbar';
export * from './SideBar';
export * from './TicketList';
export * from './TicketModal';
export * from './ListaTicketsTaller';
export * from './TicketsHistorial';
export * from './UserWidget';
export * from './HistorialPrescripciones';